allowBuilds:
  esbuild: true
  '@css-inline/css-inline': true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - 'vitest'
  - '@vitest/*'
  - '@aws-sdk/*'
  - '@css-inline/*'
  - '@yedoma-labs/*'
  - '@types/node'
