allowBuilds:
  esbuild: true
  '@css-inline/css-inline': true

minimumReleaseAgeExclude:
  - '@vitest/coverage-v8@4.1.9'
  - '@vitest/expect@4.1.9'
  - '@vitest/mocker@4.1.9'
  - '@vitest/pretty-format@4.1.9'
  - '@vitest/runner@4.1.9'
  - '@vitest/snapshot@4.1.9'
  - '@vitest/spy@4.1.9'
  - '@vitest/utils@4.1.9'
  - '@yedoma-labs/tuuru-chrono-tz@0.3.1'
  - vitest@4.1.9
  - '@aws-sdk/client-ses@3.1069.0'
  - '@aws-sdk/core@3.974.21'
  - '@aws-sdk/credential-provider-env@3.972.47'
  - '@aws-sdk/credential-provider-http@3.972.49'
  - '@aws-sdk/credential-provider-ini@3.972.54'
  - '@aws-sdk/credential-provider-login@3.972.53'
  - '@aws-sdk/credential-provider-node@3.972.56'
  - '@aws-sdk/credential-provider-process@3.972.47'
  - '@aws-sdk/credential-provider-sso@3.972.53'
  - '@aws-sdk/credential-provider-web-identity@3.972.53'
  - '@aws-sdk/nested-clients@3.997.21'
  - '@aws-sdk/signature-v4-multi-region@3.996.35'
  - '@aws-sdk/token-providers@3.1069.0'
  - '@aws-sdk/types@3.973.13'
  - '@aws-sdk/xml-builder@3.972.30'
  - '@aws-sdk/client-ses@3.1070.0'
  - '@css-inline/css-inline-android-arm-eabi@0.21.0'
  - '@css-inline/css-inline-android-arm64@0.21.0'
  - '@css-inline/css-inline-darwin-arm64@0.21.0'
  - '@css-inline/css-inline-darwin-x64@0.21.0'
  - '@css-inline/css-inline-linux-arm-gnueabihf@0.21.0'
  - '@css-inline/css-inline-linux-arm64-gnu@0.21.0'
  - '@css-inline/css-inline-linux-arm64-musl@0.21.0'
  - '@css-inline/css-inline-linux-x64-gnu@0.21.0'
  - '@css-inline/css-inline-linux-x64-musl@0.21.0'
  - '@css-inline/css-inline-win32-arm64-msvc@0.21.0'
  - '@css-inline/css-inline-win32-x64-msvc@0.21.0'
  - '@css-inline/css-inline@0.21.0'
