allowBuilds:
  esbuild: true
  '@css-inline/css-inline': true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - 'vitest'
  - '@vitest/*'
  - '@aws-sdk/*'
  - '@css-inline/*'
  - '@yedoma-labs/*'
  - '@types/node'
overrides:
  'postcss': '>=8.5.23'
  'source-map-js': '>=1.2.2'
  'deepmerge-ts': '>=8.0.0'
  'fast-copy': '>=4.1.0'
